config:
  validation: true
  warningsAsErrors: false

complexity:
  active: true
  LongMethod:
    active: true
    allowedLines: 99
  LongParameterList:
    active: true
    allowedFunctionParameters: 6
    allowedConstructorParameters: 7
    ignoreAnnotated:
      - 'Composable'
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 19
    allowedFunctionsPerClass: 19
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 14

style:
  active: true
  UnusedPrivateFunction:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewParameter'
  MaxLineLength:
    active: true
    maxLineLength: 120
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
  ForbiddenComment:
    active: false
  WildcardImport:
    active: true
  ReturnCount:
    active: true
    max: 4

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    ignoreAnnotated: ['Composable']

ktlint:
  active: true
  autoCorrect: true
  Indentation:
    active: true
    indentSize: 4
  FinalNewline:
    active: true